const WEB3J_MAVEN_PROPERTY_VERSION_NAME = 'web3j.version';
const WEB3J_GRADLE_PROPERTY_VERSION_NAME = 'web3j_version';
const WEB3J_PROPERTY_VERSION_VALUE = '4.5.5';

const WEB3J_GROUPID = 'org.web3j';
const WEB3J_ARTIFACTID = 'core';

const constants = {
    WEB3J_GROUPID,
    WEB3J_ARTIFACTID,
    WEB3J_MAVEN_PROPERTY_VERSION_NAME,
    WEB3J_GRADLE_PROPERTY_VERSION_NAME,
    WEB3J_PROPERTY_VERSION_VALUE
};

module.exports = constants;
